version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: pollwave-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: .
    container_name: pollwave-backend
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/pollwave
      - PORT=4000

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: pollwave-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo-data:
